name: app-aca

on:
  #  workflow_call:
  workflow_dispatch:
    inputs:
      service:
        description: 'Service'
        type: string
        required: true
      image:
        description: 'Image ref'
        type: string
        required: true
      repository:
        description: 'Repository'
        type: string
        default: ''
      target_ref:
        description: 'Target branch for edit'
        type: string
        default: 'aca-workflow'
#    secrets:
#      MONO_DEPLOY_PUSH_TOKEN:
#        required: true
# ${{ github.event.repository.name }}

concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false

permissions:
  contents: write

jobs:
  ACA:
    runs-on: ubuntu-latest
    env:
      CONFIG_FILE: primary/apps-aca.yaml
      DEPLOY_URL: https://github.com/mwierzchowski/mono-deploy/actions/workflows/primary.yaml
    steps:
      - name: 'Checkout deploy repository'
        uses: actions/checkout@v4
        with:
          repository: mwierzchowski/mono-deploy
          ref: ${{ inputs.target_ref }}
          #          token: ${{ secrets.MONO_DEPLOY_PUSH_TOKEN }}

      - name: 'Upsert configuration'
        uses: mikefarah/yq@v4
        with:
          cmd: |
            yq -i '
              .apps["${{ inputs.service }}"].repository = "${{ env.REPOSITORY }}" |
              .apps["${{ inputs.service }}"].image = "${{ inputs.image }}"
            ' "${{ env.CONFIG_FILE }}"

      - name: 'Show updated YAML'
        run: cat '${{ env.CONFIG_FILE }}'

      - name: 'Set up Terraform'
        uses: hashicorp/setup-terraform@v3

      - name: 'Validate terraform'
        working-directory: primary
        run: |
          terraform init -backend=false -input=false -no-color
          terraform validate -no-color

      - name: 'Commit changes'
        uses: EndBug/add-and-commit@v9
        with:
          add: ${{ env.CONFIG_FILE }}
          message: 'Upsert ${{ inputs.service }} configuration'

      - name: 'Show deployment link'
        run: echo "::notice ::Deployment in [progress](${{ env.DEPLOY_URL }})..."

      - name: 'Show deployment link2'
        run: |
          {
            echo '### Deployment in progress'
            echo
            echo 'Deployment in [progress](https://github.com/mwierzchowski/mono-deploy/actions/workflows/primary.yaml)'
          } >> "$GITHUB_STEP_SUMMARY"