name: preview

on:
  workflow_dispatch:
  push:
    paths: [ 'envs/preview/**' ]

concurrency:
  group: ${{github.workflow}}
  cancel-in-progress: false

permissions:
  id-token: write
  contents: read

jobs:
  Deploy:
    runs-on: ubuntu-latest
    environment: deployer
    env:
      ARM_USE_OIDC: 'true'
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      TF_IN_AUTOMATION: 'true'
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v5

      - name: 'Setup'
        uses: hashicorp/setup-terraform@v3

      - name: 'Validate'
        run: |
          terraform -chdir=./envs/preview \
                     init -input=false -no-color \
                    -backend-config=../../terraform.tfbackend
          terraform -chdir=./envs/preview validate -no-color

      - name: 'Apply'
        run: |
          terraform -chdir=./envs/preview \
                     apply -auto-approve -input=false -no-color -compact-warnings \
                    -var-file=../../terraform.tfvars